import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

// Migrated from .eslintrc.json (ESLint v9 flat config). Same ruleset as before
// (next/core-web-vitals — includes react-hooks/rules-of-hooks); only the config
// FORMAT changed so `npx eslint .` works again (legacy .eslintrc is unusable
// under ESLint v9) and survives `next lint` removal in Next 16.
const eslintConfig = [
  {
    ignores: [
      ".next/**",
      "out/**",
      "build/**",
      "node_modules/**",
      "next-env.d.ts",
      "src/types/api.d.ts", // generated by openapi-typescript
    ],
  },
  ...compat.extends("next/core-web-vitals"),
];

export default eslintConfig;
