/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description 用户登录，返回 JWT Token
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description 获取当前用户信息
         */
        get: operations["get_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update My Profile
         * @description 当前用户自助修改非敏感资料字段（目前仅 display_name）。
         *
         *     设计意图：与 admin 后台 PUT /users/{id} 解耦 —— role / is_active /
         *     password 这些安全敏感字段走专门端点，profile 字段走这里。任何已登录
         *     用户都能调，不需要 admin 权限。
         */
        patch: operations["update_my_profile_api_v1_auth_me_patch"];
        trace?: never;
    };
    "/api/v1/auth/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change My Password
         * @description 当前用户自助修改密码
         */
        post: operations["change_my_password_api_v1_auth_me_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description 列出所有用户（仅 Admin）
         */
        get: operations["list_users_api_v1_auth_users_get"];
        put?: never;
        /**
         * Create User
         * @description 创建用户（仅 Admin）
         */
        post: operations["create_user_api_v1_auth_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User
         * @description 单查用户（Admin） — 给前端编辑表单初始化用
         */
        get: operations["get_user_api_v1_auth_users__user_id__get"];
        /**
         * Update User
         * @description 更新用户（仅 Admin）
         *
         *     防误锁：admin 不能改自己的 role / is_active / password。配合 DELETE
         *     路径的"不能删自己"保护，足以保证系统始终至少有 1 个活跃 admin
         *     （操作者必然活跃 → 不能动自己 → 至少剩自己）。
         *
         *     Self 改 password 走 POST /me/password —— 该端点强制校验 current_password，
         *     防止 token 被盗后攻击者无需旧密码就能接管账号。本端点对 self 改 password
         *     返回 403，避免在 admin 后台绕过该校验。
         */
        put: operations["update_user_api_v1_auth_users__user_id__put"];
        post?: never;
        /**
         * Delete User
         * @description 硬删用户（仅 Admin）
         *
         *     FK CASCADE 一并删除其所有会话 / messages / events / artifacts。
         *     若用户当前有正在跑的 engine，被级联删的 conversation 行会被 controller
         *     post-processing 的 exists() 检查兜住（PR2a），不会撞 FK。
         *
         *     保护：admin 不能删自己。配合"不能改自己 role/is_active"，足以保证
         *     系统始终至少 1 个活跃 admin。
         */
        delete: operations["delete_user_api_v1_auth_users__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/users/{user_id}/impact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Impact
         * @description 硬删用户前的影响数据 — 返回会话数。
         *
         *     给前端 DangerConfirmModal 显示"将级联删除 N 条会话，操作不可恢复"。
         */
        get: operations["get_user_impact_api_v1_auth_users__user_id__impact_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Conversations
         * @description 列出对话列表
         */
        get: operations["list_conversations_api_v1_chat_get"];
        put?: never;
        /**
         * Send Message
         * @description 发送新消息
         *
         *     启动执行，返回 stream_url 供前端订阅。
         */
        post: operations["send_message_api_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/{conv_id}/active-stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Active Stream
         * @description 查询会话是否有活跃的执行流，用于断线重连
         */
        get: operations["get_active_stream_api_v1_chat__conv_id__active_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/{conv_id}/inject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inject Message
         * @description 向活跃执行注入消息
         *
         *     仅当 conversation 有正在运行的执行时可用。
         *     注入的消息通过 queued_message 事件进入 lead agent 的 context。
         *     前端不应重建 SSE 连接 — 事件仍通过原有 stream 推送。
         *
         *     注入内容通过 queued_message 事件持久化到 MessageEvent 表，
         *     可通过 GET /chat/{conv_id}/messages/{msg_id}/events 查询。
         *     不创建独立 Message 记录（注入是同一轮执行的补充输入，非独立对话轮次）。
         */
        post: operations["inject_message_api_v1_chat__conv_id__inject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/{conv_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Execution
         * @description 取消活跃执行
         *
         *     请求取消 conversation 当前正在运行的执行。引擎会在下一个检查点优雅退出。
         */
        post: operations["cancel_execution_api_v1_chat__conv_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/{conv_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversation
         * @description 获取对话详情（含消息树）
         */
        get: operations["get_conversation_api_v1_chat__conv_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Conversation
         * @description 删除对话
         */
        delete: operations["delete_conversation_api_v1_chat__conv_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/{conv_id}/messages/{msg_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Message Events
         * @description 查询消息的事件链（用于历史回放和可观测性）
         */
        get: operations["get_message_events_api_v1_chat__conv_id__messages__msg_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/{conv_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Execution
         * @description 恢复中断的执行（权限确认后）
         *
         *     通过 RuntimeStore.resolve_interrupt() 唤醒暂停的 coroutine。
         */
        post: operations["resume_execution_api_v1_chat__conv_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload File New Session
         * @description Upload a file and create a new conversation for it.
         *     Use this when no session/conversation exists yet.
         */
        post: operations["upload_file_new_session_api_v1_artifacts_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Artifacts
         * @description 列出 session 下所有 artifacts
         */
        get: operations["list_artifacts_api_v1_artifacts__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{session_id}/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload File
         * @description Upload a file and create an artifact from it.
         *     Supports text files, markdown, code, PDF, and Word documents.
         */
        post: operations["upload_file_api_v1_artifacts__session_id__upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{session_id}/{artifact_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Artifact
         * @description Export an artifact to a different format.
         *     Currently supports exporting text/markdown artifacts to docx.
         *
         *     Note: reads from DB only — during execution, exports the last flushed
         *     version, not in-memory edits.  Frontend hides export while streaming.
         */
        get: operations["export_artifact_api_v1_artifacts__session_id___artifact_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{session_id}/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Artifact
         * @description 获取 artifact 当前内容和版本列表
         */
        get: operations["get_artifact_api_v1_artifacts__session_id___artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{session_id}/{artifact_id}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Version
         * @description 获取特定版本的完整内容
         *
         *     Note: DB-only — unflushed in-memory versions return 404.
         *     Frontend hides version selector while streaming, so this is unreachable
         *     for versions that only exist in cache.
         */
        get: operations["get_version_api_v1_artifacts__session_id___artifact_id__versions__version__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stream/{stream_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Events
         * @description SSE 端点，订阅执行过程
         *
         *     前端通过 EventSource 连接此端点，接收实时事件流。
         *     stream_id 即 message_id（消息与执行 1:1）。
         *
         *     事件格式（使用标准 SSE event: 字段区分事件类型）：
         *         event: metadata
         *         data: {"type": "metadata", "timestamp": "...", "data": {...}}
         *
         *         event: llm_chunk
         *         data: {"type": "llm_chunk", "timestamp": "...", "agent": "lead_agent", "data": {"content": "..."}}
         *
         *         event: complete
         *         data: {"type": "complete", "timestamp": "...", "data": {...}}
         *
         *     连接生命周期：
         *         - 收到 complete/error 事件后，服务端主动关闭连接
         *         - 前端应销毁 EventSource 实例
         */
        get: operations["stream_events_api_v1_stream__stream_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Admin Conversations
         * @description List all conversations (admin view) with active execution status.
         */
        get: operations["list_admin_conversations_api_v1_admin_conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/conversations/{conv_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Admin Conversation Events
         * @description Get all events for a conversation, grouped by message.
         */
        get: operations["get_admin_conversation_events_api_v1_admin_conversations__conv_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Departments
         * @description 列出某父下的子部门（按 name 排序）。
         *
         *     parent_id 缺省 → 一级部门；传具体 id → 该部门的直接子。
         *     给前端 cascader 每级渲染用。
         */
        get: operations["list_departments_api_v1_departments_get"];
        put?: never;
        /**
         * Create Department
         * @description 显式创建部门（admin 在管理 UI 中点 "+ 新建" 走这里）。
         *
         *     冲突 → 409。批量导入 / 创建用户时的"路径解析自动建" 走 /resolve 端点。
         */
        post: operations["create_department_api_v1_departments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tree
         * @description 返回完整部门树（顶层节点列表 → children 嵌套）。
         *
         *     一次性返回，部门表数量级别小（几十到几百）。给部门管理面板用。
         *     user_count 是该节点的**直属**用户数，子树合计由前端按需计算。
         */
        get: operations["get_tree_api_v1_departments_tree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments/{dept_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Department
         * @description 单个部门详情（含 user_count, child_count，给详情/删除前置展示用）
         */
        get: operations["get_department_api_v1_departments__dept_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Department
         * @description 删除部门 — 必须为空（无子部门、无直属用户）。
         *
         *     非空 → 409 + body 含 user_count/child_count，前端据此提示先迁。
         *     parent_id ondelete=RESTRICT 在 DB 层兜底，但路由层先校验给出更友好错误。
         */
        delete: operations["delete_department_api_v1_departments__dept_id__delete"];
        options?: never;
        head?: never;
        /**
         * Rename Department
         * @description 仅改部门名（搬家走 POST /{id}/move，路径分离避免 PATCH 字段歧义）。
         *
         *     冲突（同父下重名） → 409。
         */
        patch: operations["rename_department_api_v1_departments__dept_id__patch"];
        trace?: never;
    };
    "/api/v1/departments/{dept_id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move Department
         * @description 搬家：把部门挂到新父下。new_parent_id=None → 搬到根。
         *
         *     校验：
         *     - 环检测：不能搬到自己 / 自己子孙下 → 400
         *     - 名称冲突：新父下已有同名 → 409
         *     - 新父不存在 → 400
         */
        post: operations["move_department_api_v1_departments__dept_id__move_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Path
         * @description 路径 → 末级 dept_id。缺失层级自动创建（admin 显式提交，安全）。
         *
         *     给前端 cascader "+ 新建当前级" 入口、PR3 批量导入时按行解析用。
         *     空路径 / 全空字符串 → 返回 {id: null}。
         */
        post: operations["resolve_path_api_v1_departments_resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["liveness_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdminConversationEventsResponse
         * @description GET /api/v1/admin/conversations/{conv_id}/events response
         */
        AdminConversationEventsResponse: {
            /** Conversation Id */
            conversation_id: string;
            /** Title */
            title: string | null;
            /** Messages */
            messages: components["schemas"]["AdminMessageGroup"][];
        };
        /**
         * AdminConversationListResponse
         * @description GET /api/v1/admin/conversations response
         */
        AdminConversationListResponse: {
            /** Conversations */
            conversations: components["schemas"]["AdminConversationSummary"][];
            /** Total */
            total: number;
            /** Has More */
            has_more: boolean;
        };
        /**
         * AdminConversationSummary
         * @description Conversation summary for admin view
         */
        AdminConversationSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string | null;
            /** User Id */
            user_id: string | null;
            /** User Display Name */
            user_display_name: string | null;
            /**
             * Message Count
             * @default 0
             */
            message_count: number;
            /**
             * Is Active
             * @default false
             */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * AdminEventItem
         * @description Single event in admin event timeline
         */
        AdminEventItem: {
            /** Id */
            id: number;
            /** Event Type */
            event_type: string;
            /** Agent Name */
            agent_name: string | null;
            /** Data */
            data: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * AdminMessageGroup
         * @description Events grouped by message
         */
        AdminMessageGroup: {
            /** Message Id */
            message_id: string;
            /** User Input */
            user_input: string;
            /** Response */
            response: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Events */
            events: components["schemas"]["AdminEventItem"][];
            /** Execution Metrics */
            execution_metrics: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ArtifactListResponse
         * @description GET /api/v1/artifacts/{session_id} response
         */
        ArtifactListResponse: {
            /**
             * Session Id
             * @description Session ID
             */
            session_id: string;
            /**
             * Artifacts
             * @description Artifact list
             */
            artifacts: components["schemas"]["ArtifactSummary"][];
        };
        /**
         * ArtifactResponse
         * @description GET /api/v1/artifacts/{session_id}/{artifact_id} response
         */
        ArtifactResponse: {
            /**
             * Id
             * @description Artifact ID
             */
            id: string;
            /**
             * Session Id
             * @description Session ID
             */
            session_id: string;
            /**
             * Content Type
             * @description Content type
             */
            content_type: string;
            /**
             * Title
             * @description Artifact title
             */
            title: string;
            /**
             * Content
             * @description Current version content
             */
            content: string;
            /**
             * Current Version
             * @description Current version number
             */
            current_version: number;
            /**
             * Source
             * @description Source (agent, user_upload)
             */
            source: string | null;
            /**
             * Original Filename
             * @description For source=user_upload artifacts: the filename the user uploaded. From metadata['original_filename'].
             */
            original_filename: string | null;
            /**
             * Created At
             * Format: date-time
             * @description Creation time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description Last update time
             */
            updated_at: string;
            /**
             * Versions
             * @description All version summaries
             */
            versions: components["schemas"]["VersionSummary"][];
        };
        /**
         * ArtifactSummary
         * @description Artifact summary in list response
         */
        ArtifactSummary: {
            /**
             * Id
             * @description Artifact ID
             */
            id: string;
            /**
             * Content Type
             * @description Content type (MIME type, e.g. text/markdown, text/x-python)
             */
            content_type: string;
            /**
             * Title
             * @description Artifact title
             */
            title: string;
            /**
             * Current Version
             * @description Current version number
             */
            current_version: number;
            /**
             * Source
             * @description Source (agent, user_upload)
             */
            source: string | null;
            /**
             * Original Filename
             * @description For source=user_upload artifacts: the filename the user uploaded. From metadata['original_filename'].
             */
            original_filename: string | null;
            /**
             * Created At
             * Format: date-time
             * @description Creation time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description Last update time
             */
            updated_at: string;
        };
        /** Body_upload_file_api_v1_artifacts__session_id__upload_post */
        Body_upload_file_api_v1_artifacts__session_id__upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** Body_upload_file_new_session_api_v1_artifacts_upload_post */
        Body_upload_file_new_session_api_v1_artifacts_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /**
         * CancelResponse
         * @description POST /api/v1/chat/{conv_id}/cancel response
         */
        CancelResponse: {
            /**
             * Message Id
             * @description Cancelled execution message ID
             */
            message_id: string;
        };
        /**
         * ChangePasswordRequest
         * @description POST /api/v1/auth/me/password request body
         */
        ChangePasswordRequest: {
            /**
             * Current Password
             * @description Current password
             */
            current_password: string;
            /**
             * New Password
             * @description New password
             */
            new_password: string;
        };
        /**
         * ChatRequest
         * @description POST /api/v1/chat request body
         */
        ChatRequest: {
            /**
             * User Input
             * @description User message content
             */
            user_input: string;
            /**
             * Conversation Id
             * @description Continue existing conversation
             */
            conversation_id?: string | null;
            /**
             * Parent Message Id
             * @description Branch from specific message
             */
            parent_message_id?: string | null;
        };
        /**
         * ChatResponse
         * @description POST /api/v1/chat response
         */
        ChatResponse: {
            /**
             * Conversation Id
             * @description Conversation ID
             */
            conversation_id: string;
            /**
             * Message Id
             * @description New message ID
             */
            message_id: string;
            /**
             * Stream Url
             * @description SSE endpoint URL for streaming
             */
            stream_url: string;
        };
        /**
         * ConversationDetailResponse
         * @description GET /api/v1/chat/{conv_id} response
         */
        ConversationDetailResponse: {
            /**
             * Id
             * @description Conversation ID
             */
            id: string;
            /**
             * Title
             * @description Conversation title
             */
            title: string | null;
            /**
             * Active Branch
             * @description Current active branch message ID
             */
            active_branch: string | null;
            /**
             * Messages
             * @description All messages (flat array with tree structure)
             */
            messages: components["schemas"]["MessageResponse"][];
            /**
             * Session Id
             * @description Associated artifact session ID
             */
            session_id: string;
            /**
             * Created At
             * Format: date-time
             * @description Creation time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description Last update time
             */
            updated_at: string;
        };
        /**
         * ConversationListResponse
         * @description GET /api/v1/chat response
         */
        ConversationListResponse: {
            /**
             * Conversations
             * @description Conversation list
             */
            conversations: components["schemas"]["ConversationSummary"][];
            /**
             * Total
             * @description Total count
             */
            total: number;
            /**
             * Has More
             * @description Whether more results exist
             */
            has_more: boolean;
        };
        /**
         * ConversationSummary
         * @description Conversation summary in list response
         */
        ConversationSummary: {
            /**
             * Id
             * @description Conversation ID
             */
            id: string;
            /**
             * Title
             * @description Conversation title
             */
            title: string | null;
            /**
             * Message Count
             * @description Number of messages
             * @default 0
             */
            message_count: number;
            /**
             * Created At
             * Format: date-time
             * @description Creation time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description Last update time
             */
            updated_at: string;
        };
        /**
         * CreateDepartmentRequest
         * @description POST /api/v1/departments request body
         */
        CreateDepartmentRequest: {
            /**
             * Name
             * @description Department name
             */
            name: string;
            /**
             * Parent Id
             * @description Parent department id; null = top-level
             */
            parent_id?: string | null;
        };
        /**
         * CreateUserRequest
         * @description POST /api/v1/auth/users request body
         */
        CreateUserRequest: {
            /**
             * Username
             * @description Username
             */
            username: string;
            /**
             * Password
             * @description Password
             */
            password: string;
            /**
             * Display Name
             * @description Display name
             */
            display_name?: string | null;
            /**
             * Role
             * @description Role (admin or user)
             * @default user
             */
            role: string;
            /**
             * Department Id
             * @description Department id; null = unassigned
             */
            department_id?: string | null;
        };
        /**
         * DepartmentListResponse
         * @description GET /api/v1/departments response — 同级列表
         */
        DepartmentListResponse: {
            /** Departments */
            departments: components["schemas"]["DepartmentResponse"][];
        };
        /**
         * DepartmentResponse
         * @description Single department response (含直属计数)
         */
        DepartmentResponse: {
            /** Id */
            id: string;
            /** Parent Id */
            parent_id: string | null;
            /** Name */
            name: string;
            /**
             * User Count
             * @description 该部门下直属用户数（不含子部门）
             */
            user_count: number;
            /**
             * Child Count
             * @description 直接子部门数
             */
            child_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * DepartmentTreeNode
         * @description Tree node — 递归结构，包含 children
         */
        DepartmentTreeNode: {
            /** Id */
            id: string;
            /** Parent Id */
            parent_id: string | null;
            /** Name */
            name: string;
            /**
             * User Count
             * @description 该部门下直属用户数
             */
            user_count: number;
            /** Children */
            children: components["schemas"]["DepartmentTreeNode"][];
        };
        /**
         * DepartmentTreeResponse
         * @description GET /api/v1/departments/tree response — 顶层节点列表
         */
        DepartmentTreeResponse: {
            /** Nodes */
            nodes: components["schemas"]["DepartmentTreeNode"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail: components["schemas"]["ValidationError"][];
        };
        /**
         * InjectRequest
         * @description POST /api/v1/chat/{conv_id}/inject request body
         */
        InjectRequest: {
            /**
             * Content
             * @description Message content to inject into the active execution
             */
            content: string;
        };
        /**
         * InjectResponse
         * @description POST /api/v1/chat/{conv_id}/inject response
         */
        InjectResponse: {
            /**
             * Message Id
             * @description Active execution message ID that received the injection
             */
            message_id: string;
            /**
             * Stream Url
             * @description Existing SSE stream URL (already connected, do not reconnect)
             */
            stream_url: string;
        };
        /**
         * LoginRequest
         * @description POST /api/v1/auth/login request body
         */
        LoginRequest: {
            /**
             * Username
             * @description Username
             */
            username: string;
            /**
             * Password
             * @description Password
             */
            password: string;
        };
        /**
         * LoginResponse
         * @description POST /api/v1/auth/login response
         */
        LoginResponse: {
            /**
             * Access Token
             * @description JWT access token
             */
            access_token: string;
            /**
             * Token Type
             * @description Token type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires In
             * @description Token expiry in seconds
             */
            expires_in: number;
            /** @description User info */
            user: components["schemas"]["UserInfo"];
        };
        /**
         * MessageResponse
         * @description Message in conversation detail response
         */
        MessageResponse: {
            /**
             * Id
             * @description Message ID
             */
            id: string;
            /**
             * Parent Id
             * @description Parent message ID
             */
            parent_id: string | null;
            /**
             * User Input
             * @description User message content
             */
            user_input: string;
            /**
             * Response
             * @description Assistant response
             */
            response: string | null;
            /**
             * Created At
             * Format: date-time
             * @description Message creation time
             */
            created_at: string;
            /**
             * Children
             * @description Child message IDs
             */
            children: string[];
            /**
             * Execution Metrics
             * @description Turn-level metrics from Message.metadata_['execution_metrics']: started_at, completed_at, total_duration_ms, total_token_usage, etc.
             */
            execution_metrics: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * MoveDepartmentRequest
         * @description POST /api/v1/departments/{id}/move request body — 搬家
         */
        MoveDepartmentRequest: {
            /**
             * New Parent Id
             * @description New parent id; null = move to root
             */
            new_parent_id?: string | null;
        };
        /**
         * ResolveDepartmentRequest
         * @description POST /api/v1/departments/resolve request body
         */
        ResolveDepartmentRequest: {
            /**
             * Path
             * @description Department path from top to leaf; empty list → null id
             */
            path: string[];
        };
        /**
         * ResolveDepartmentResponse
         * @description POST /api/v1/departments/resolve response
         */
        ResolveDepartmentResponse: {
            /**
             * Id
             * @description 末级部门 id；空 path → null
             */
            id: string | null;
        };
        /**
         * ResumeRequest
         * @description POST /api/v1/chat/{conv_id}/resume request body
         */
        ResumeRequest: {
            /**
             * Message Id
             * @description Message ID to resume
             */
            message_id: string;
            /**
             * Approved
             * @description Whether the permission was approved
             */
            approved: boolean;
            /**
             * Always Allow
             * @description Always allow this tool for the rest of this execution
             * @default false
             */
            always_allow: boolean;
        };
        /**
         * ResumeResponse
         * @description POST /api/v1/chat/{conv_id}/resume response
         */
        ResumeResponse: {
            /**
             * Stream Url
             * @description New SSE endpoint URL
             */
            stream_url: string;
        };
        /**
         * UpdateDepartmentRequest
         * @description PATCH /api/v1/departments/{id} request body — 仅改名
         */
        UpdateDepartmentRequest: {
            /**
             * Name
             * @description New department name
             */
            name: string;
        };
        /**
         * UpdateMyProfileRequest
         * @description PATCH /api/v1/auth/me request body — 自助修改自己的非敏感资料字段
         */
        UpdateMyProfileRequest: {
            /**
             * Display Name
             * @description Display name; pass empty string to clear
             */
            display_name?: string | null;
        };
        /**
         * UpdateUserRequest
         * @description PUT /api/v1/auth/users/{id} request body.
         *
         *     All fields optional. department_id semantics: 字段被显式传入时生效（包括
         *     传 null = 清空归属）；字段缺省 → 不改。路由通过 model_fields_set 区分。
         */
        UpdateUserRequest: {
            /**
             * Display Name
             * @description Display name
             */
            display_name?: string | null;
            /**
             * Password
             * @description New password
             */
            password?: string | null;
            /**
             * Role
             * @description Role (admin or user)
             */
            role?: string | null;
            /**
             * Is Active
             * @description Whether user is active
             */
            is_active?: boolean | null;
            /**
             * Department Id
             * @description Department id; explicit null clears
             */
            department_id?: string | null;
        };
        /**
         * UploadResponse
         * @description POST /api/v1/artifacts/{session_id}/upload response
         */
        UploadResponse: {
            /**
             * Id
             * @description Artifact ID
             */
            id: string;
            /**
             * Session Id
             * @description Session ID
             */
            session_id: string;
            /**
             * Content Type
             * @description MIME type (after conversion)
             */
            content_type: string;
            /**
             * Title
             * @description Artifact title
             */
            title: string;
            /**
             * Current Version
             * @description Current version number
             */
            current_version: number;
            /**
             * Source
             * @description Source (user_upload)
             */
            source: string;
            /**
             * Original Filename
             * @description Original uploaded filename
             */
            original_filename: string;
            /**
             * Created At
             * Format: date-time
             * @description Creation time
             */
            created_at: string;
        };
        /**
         * UserImpactResponse
         * @description GET /api/v1/auth/users/{id}/impact response
         *
         *     给前端硬删用户前的二次确认弹窗显示影响数据。
         */
        UserImpactResponse: {
            /**
             * Conversation Count
             * @description 该用户拥有的对话数（CASCADE 删除时一并丢失）
             */
            conversation_count: number;
        };
        /**
         * UserInfo
         * @description User info in responses
         */
        UserInfo: {
            /**
             * Id
             * @description User ID
             */
            id: string;
            /**
             * Username
             * @description Username
             */
            username: string;
            /**
             * Display Name
             * @description Display name
             */
            display_name: string | null;
            /**
             * Role
             * @description Role
             */
            role: string;
        };
        /**
         * UserListResponse
         * @description GET /api/v1/auth/users response
         */
        UserListResponse: {
            /** Users */
            users: components["schemas"]["UserResponse"][];
            /** Total */
            total: number;
        };
        /**
         * UserResponse
         * @description Single user response (admin)
         */
        UserResponse: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /** Display Name */
            display_name: string | null;
            /** Role */
            role: string;
            /** Is Active */
            is_active: boolean;
            /** Department Id */
            department_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VersionDetailResponse
         * @description GET /api/v1/artifacts/{session_id}/{artifact_id}/versions/{version} response
         */
        VersionDetailResponse: {
            /**
             * Version
             * @description Version number
             */
            version: number;
            /**
             * Content
             * @description Version content
             */
            content: string;
            /**
             * Update Type
             * @description Update type
             */
            update_type: string;
            /**
             * Created At
             * Format: date-time
             * @description Version creation time
             */
            created_at: string;
        };
        /**
         * VersionSummary
         * @description Version summary in version list response
         */
        VersionSummary: {
            /**
             * Version
             * @description Version number
             */
            version: number;
            /**
             * Update Type
             * @description Update type (create, update, update_fuzzy, rewrite)
             */
            update_type: string;
            /**
             * Created At
             * Format: date-time
             * @description Version creation time
             */
            created_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInfo"];
                };
            };
        };
    };
    update_my_profile_api_v1_auth_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMyProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_my_password_api_v1_auth_me_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_auth_users_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_v1_auth_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_api_v1_auth_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_auth_users__user_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_v1_auth_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_impact_api_v1_auth_users__user_id__impact_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserImpactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_api_v1_chat_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_api_v1_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_active_stream_api_v1_chat__conv_id__active_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conv_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inject_message_api_v1_chat__conv_id__inject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conv_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InjectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_execution_api_v1_chat__conv_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conv_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_v1_chat__conv_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conv_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_api_v1_chat__conv_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conv_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_message_events_api_v1_chat__conv_id__messages__msg_id__events_get: {
        parameters: {
            query?: {
                /** @description Filter by event type */
                event_type?: string | null;
            };
            header?: never;
            path: {
                conv_id: string;
                msg_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_execution_api_v1_chat__conv_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conv_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_file_new_session_api_v1_artifacts_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_new_session_api_v1_artifacts_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_artifacts_api_v1_artifacts__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_file_api_v1_artifacts__session_id__upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_api_v1_artifacts__session_id__upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_artifact_api_v1_artifacts__session_id___artifact_id__export_get: {
        parameters: {
            query: {
                /** @description Export format (docx) */
                format: string;
            };
            header?: never;
            path: {
                session_id: string;
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_api_v1_artifacts__session_id___artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_version_api_v1_artifacts__session_id___artifact_id__versions__version__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                artifact_id: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_api_v1_stream__stream_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_admin_conversations_api_v1_admin_conversations_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                q?: string | null;
                user_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminConversationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_admin_conversation_events_api_v1_admin_conversations__conv_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conv_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminConversationEventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_departments_api_v1_departments_get: {
        parameters: {
            query?: {
                /** @description Parent id; omit for top-level */
                parent_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_department_api_v1_departments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDepartmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tree_api_v1_departments_tree_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentTreeResponse"];
                };
            };
        };
    };
    get_department_api_v1_departments__dept_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dept_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_department_api_v1_departments__dept_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dept_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_department_api_v1_departments__dept_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dept_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDepartmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_department_api_v1_departments__dept_id__move_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dept_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveDepartmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_path_api_v1_departments_resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveDepartmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveDepartmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    liveness_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
