/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description 用户登录，返回 JWT Token
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description 获取当前用户信息
         */
        get: operations["get_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description 列出所有用户（仅 Admin）
         */
        get: operations["list_users_api_v1_auth_users_get"];
        put?: never;
        /**
         * Create User
         * @description 创建用户（仅 Admin）
         */
        post: operations["create_user_api_v1_auth_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update User
         * @description 更新用户（仅 Admin）
         */
        put: operations["update_user_api_v1_auth_users__user_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Conversations
         * @description 列出对话列表
         */
        get: operations["list_conversations_api_v1_chat_get"];
        put?: never;
        /**
         * Send Message
         * @description 发送新消息
         *
         *     启动执行，返回 stream_url 供前端订阅。
         */
        post: operations["send_message_api_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/{conv_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversation
         * @description 获取对话详情（含消息树）
         */
        get: operations["get_conversation_api_v1_chat__conv_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Conversation
         * @description 删除对话
         */
        delete: operations["delete_conversation_api_v1_chat__conv_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/{conv_id}/messages/{msg_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Message Events
         * @description 查询消息的事件链（用于历史回放和可观测性）
         */
        get: operations["get_message_events_api_v1_chat__conv_id__messages__msg_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/{conv_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Execution
         * @description 恢复中断的执行（权限确认后）
         *
         *     v2: 直接通过 TaskManager.resolve_interrupt() 唤醒暂停的 coroutine，
         *     不再创建新的 controller/graph。
         */
        post: operations["resume_execution_api_v1_chat__conv_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload File New Session
         * @description Upload a file and create a new conversation for it.
         *     Use this when no session/conversation exists yet.
         */
        post: operations["upload_file_new_session_api_v1_artifacts_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Artifacts
         * @description 列出 session 下所有 artifacts
         */
        get: operations["list_artifacts_api_v1_artifacts__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{session_id}/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload File
         * @description Upload a file and create an artifact from it.
         *     Supports text files, markdown, code, PDF, and Word documents.
         */
        post: operations["upload_file_api_v1_artifacts__session_id__upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{session_id}/{artifact_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Artifact
         * @description Export an artifact to a different format.
         *     Currently supports exporting text/markdown artifacts to docx.
         */
        get: operations["export_artifact_api_v1_artifacts__session_id___artifact_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{session_id}/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Artifact
         * @description 获取 artifact 详情（包含当前版本内容）
         */
        get: operations["get_artifact_api_v1_artifacts__session_id___artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{session_id}/{artifact_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Versions
         * @description 获取版本历史列表
         */
        get: operations["list_versions_api_v1_artifacts__session_id___artifact_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{session_id}/{artifact_id}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Version
         * @description 获取特定版本的完整内容
         */
        get: operations["get_version_api_v1_artifacts__session_id___artifact_id__versions__version__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stream/{stream_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Events
         * @description SSE 端点，订阅执行过程
         *
         *     前端通过 EventSource 连接此端点，接收实时事件流。
         *     stream_id 即 message_id（消息与执行 1:1）。
         *
         *     事件格式（使用标准 SSE event: 字段区分事件类型）：
         *         event: metadata
         *         data: {"type": "metadata", "timestamp": "...", "data": {...}}
         *
         *         event: llm_chunk
         *         data: {"type": "llm_chunk", "timestamp": "...", "agent": "lead_agent", "data": {"content": "..."}}
         *
         *         event: complete
         *         data: {"type": "complete", "timestamp": "...", "data": {...}}
         *
         *     连接生命周期：
         *         - 收到 complete/error 事件后，服务端主动关闭连接
         *         - 前端应销毁 EventSource 实例
         */
        get: operations["stream_events_api_v1_stream__stream_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ArtifactDetailResponse
         * @description GET /api/v1/artifacts/{session_id}/{artifact_id} response
         */
        ArtifactDetailResponse: {
            /**
             * Id
             * @description Artifact ID
             */
            id: string;
            /**
             * Session Id
             * @description Session ID
             */
            session_id: string;
            /**
             * Content Type
             * @description Content type
             */
            content_type: string;
            /**
             * Title
             * @description Artifact title
             */
            title: string;
            /**
             * Content
             * @description Current version content
             */
            content: string;
            /**
             * Current Version
             * @description Current version number
             */
            current_version: number;
            /**
             * Source
             * @description Source (agent, user_upload)
             */
            source: string | null;
            /**
             * Created At
             * Format: date-time
             * @description Creation time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description Last update time
             */
            updated_at: string;
        };
        /**
         * ArtifactListResponse
         * @description GET /api/v1/artifacts/{session_id} response
         */
        ArtifactListResponse: {
            /**
             * Session Id
             * @description Session ID
             */
            session_id: string;
            /**
             * Artifacts
             * @description Artifact list
             */
            artifacts: components["schemas"]["ArtifactSummary"][];
        };
        /**
         * ArtifactSummary
         * @description Artifact summary in list response
         */
        ArtifactSummary: {
            /**
             * Id
             * @description Artifact ID
             */
            id: string;
            /**
             * Content Type
             * @description Content type (MIME type, e.g. text/markdown, text/x-python)
             */
            content_type: string;
            /**
             * Title
             * @description Artifact title
             */
            title: string;
            /**
             * Current Version
             * @description Current version number
             */
            current_version: number;
            /**
             * Source
             * @description Source (agent, user_upload)
             */
            source: string | null;
            /**
             * Created At
             * Format: date-time
             * @description Creation time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description Last update time
             */
            updated_at: string;
        };
        /** Body_upload_file_api_v1_artifacts__session_id__upload_post */
        Body_upload_file_api_v1_artifacts__session_id__upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** Body_upload_file_new_session_api_v1_artifacts_upload_post */
        Body_upload_file_new_session_api_v1_artifacts_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /**
         * ChatRequest
         * @description POST /api/v1/chat request body
         */
        ChatRequest: {
            /**
             * Content
             * @description User message content
             */
            content: string;
            /**
             * Conversation Id
             * @description Continue existing conversation
             */
            conversation_id?: string | null;
            /**
             * Parent Message Id
             * @description Branch from specific message
             */
            parent_message_id?: string | null;
        };
        /**
         * ChatResponse
         * @description POST /api/v1/chat response
         */
        ChatResponse: {
            /**
             * Conversation Id
             * @description Conversation ID
             */
            conversation_id: string;
            /**
             * Message Id
             * @description New message ID
             */
            message_id: string;
            /**
             * Stream Url
             * @description SSE endpoint URL for streaming
             */
            stream_url: string;
        };
        /**
         * ConversationDetailResponse
         * @description GET /api/v1/chat/{conv_id} response
         */
        ConversationDetailResponse: {
            /**
             * Id
             * @description Conversation ID
             */
            id: string;
            /**
             * Title
             * @description Conversation title
             */
            title: string | null;
            /**
             * Active Branch
             * @description Current active branch message ID
             */
            active_branch: string | null;
            /**
             * Messages
             * @description All messages (flat array with tree structure)
             */
            messages: components["schemas"]["MessageResponse"][];
            /**
             * Session Id
             * @description Associated artifact session ID
             */
            session_id: string;
            /**
             * Created At
             * Format: date-time
             * @description Creation time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description Last update time
             */
            updated_at: string;
        };
        /**
         * ConversationListResponse
         * @description GET /api/v1/chat response
         */
        ConversationListResponse: {
            /**
             * Conversations
             * @description Conversation list
             */
            conversations: components["schemas"]["ConversationSummary"][];
            /**
             * Total
             * @description Total count
             */
            total: number;
            /**
             * Has More
             * @description Whether more results exist
             */
            has_more: boolean;
        };
        /**
         * ConversationSummary
         * @description Conversation summary in list response
         */
        ConversationSummary: {
            /**
             * Id
             * @description Conversation ID
             */
            id: string;
            /**
             * Title
             * @description Conversation title
             */
            title: string | null;
            /**
             * Message Count
             * @description Number of messages
             * @default 0
             */
            message_count: number;
            /**
             * Created At
             * Format: date-time
             * @description Creation time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description Last update time
             */
            updated_at: string;
        };
        /**
         * CreateUserRequest
         * @description POST /api/v1/auth/users request body
         */
        CreateUserRequest: {
            /**
             * Username
             * @description Username
             */
            username: string;
            /**
             * Password
             * @description Password
             */
            password: string;
            /**
             * Display Name
             * @description Display name
             */
            display_name?: string | null;
            /**
             * Role
             * @description Role (admin or user)
             * @default user
             */
            role: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail: components["schemas"]["ValidationError"][];
        };
        /**
         * LoginRequest
         * @description POST /api/v1/auth/login request body
         */
        LoginRequest: {
            /**
             * Username
             * @description Username
             */
            username: string;
            /**
             * Password
             * @description Password
             */
            password: string;
        };
        /**
         * LoginResponse
         * @description POST /api/v1/auth/login response
         */
        LoginResponse: {
            /**
             * Access Token
             * @description JWT access token
             */
            access_token: string;
            /**
             * Token Type
             * @description Token type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires In
             * @description Token expiry in seconds
             */
            expires_in: number;
            /** @description User info */
            user: components["schemas"]["UserInfo"];
        };
        /**
         * MessageResponse
         * @description Message in conversation detail response
         */
        MessageResponse: {
            /**
             * Id
             * @description Message ID
             */
            id: string;
            /**
             * Parent Id
             * @description Parent message ID
             */
            parent_id: string | null;
            /**
             * Content
             * @description User message content
             */
            content: string;
            /**
             * Response
             * @description Assistant response
             */
            response: string | null;
            /**
             * Created At
             * Format: date-time
             * @description Message creation time
             */
            created_at: string;
            /**
             * Children
             * @description Child message IDs
             */
            children: string[];
        };
        /**
         * ResumeRequest
         * @description POST /api/v1/chat/{conv_id}/resume request body
         */
        ResumeRequest: {
            /**
             * Message Id
             * @description Message ID to resume
             */
            message_id: string;
            /**
             * Approved
             * @description Whether the permission was approved
             */
            approved: boolean;
            /**
             * Always Allow
             * @description Always allow this tool for the rest of this execution
             * @default false
             */
            always_allow: boolean;
        };
        /**
         * ResumeResponse
         * @description POST /api/v1/chat/{conv_id}/resume response
         */
        ResumeResponse: {
            /**
             * Stream Url
             * @description New SSE endpoint URL
             */
            stream_url: string;
        };
        /**
         * UpdateUserRequest
         * @description PUT /api/v1/auth/users/{id} request body
         */
        UpdateUserRequest: {
            /**
             * Display Name
             * @description Display name
             */
            display_name?: string | null;
            /**
             * Password
             * @description New password
             */
            password?: string | null;
            /**
             * Role
             * @description Role (admin or user)
             */
            role?: string | null;
            /**
             * Is Active
             * @description Whether user is active
             */
            is_active?: boolean | null;
        };
        /**
         * UploadResponse
         * @description POST /api/v1/artifacts/{session_id}/upload response
         */
        UploadResponse: {
            /**
             * Id
             * @description Artifact ID
             */
            id: string;
            /**
             * Session Id
             * @description Session ID
             */
            session_id: string;
            /**
             * Content Type
             * @description MIME type (after conversion)
             */
            content_type: string;
            /**
             * Title
             * @description Artifact title
             */
            title: string;
            /**
             * Current Version
             * @description Current version number
             */
            current_version: number;
            /**
             * Source
             * @description Source (user_upload)
             */
            source: string;
            /**
             * Original Filename
             * @description Original uploaded filename
             */
            original_filename: string;
            /**
             * Created At
             * Format: date-time
             * @description Creation time
             */
            created_at: string;
        };
        /**
         * UserInfo
         * @description User info in responses
         */
        UserInfo: {
            /**
             * Id
             * @description User ID
             */
            id: string;
            /**
             * Username
             * @description Username
             */
            username: string;
            /**
             * Display Name
             * @description Display name
             */
            display_name: string | null;
            /**
             * Role
             * @description Role
             */
            role: string;
        };
        /**
         * UserListResponse
         * @description GET /api/v1/auth/users response
         */
        UserListResponse: {
            /** Users */
            users: components["schemas"]["UserResponse"][];
            /** Total */
            total: number;
        };
        /**
         * UserResponse
         * @description Single user response (admin)
         */
        UserResponse: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /** Display Name */
            display_name: string | null;
            /** Role */
            role: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VersionDetailResponse
         * @description GET /api/v1/artifacts/{session_id}/{artifact_id}/versions/{version} response
         */
        VersionDetailResponse: {
            /**
             * Version
             * @description Version number
             */
            version: number;
            /**
             * Content
             * @description Version content
             */
            content: string;
            /**
             * Update Type
             * @description Update type
             */
            update_type: string;
            /**
             * Changes
             * @description Changes [[old, new], ...]
             */
            changes: string[][] | null;
            /**
             * Created At
             * Format: date-time
             * @description Version creation time
             */
            created_at: string;
        };
        /**
         * VersionListResponse
         * @description GET /api/v1/artifacts/{session_id}/{artifact_id}/versions response
         */
        VersionListResponse: {
            /**
             * Artifact Id
             * @description Artifact ID
             */
            artifact_id: string;
            /**
             * Session Id
             * @description Session ID
             */
            session_id: string;
            /**
             * Versions
             * @description Version list
             */
            versions: components["schemas"]["VersionSummary"][];
        };
        /**
         * VersionSummary
         * @description Version summary in version list response
         */
        VersionSummary: {
            /**
             * Version
             * @description Version number
             */
            version: number;
            /**
             * Update Type
             * @description Update type (create, update, update_fuzzy, rewrite)
             */
            update_type: string;
            /**
             * Created At
             * Format: date-time
             * @description Version creation time
             */
            created_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInfo"];
                };
            };
        };
    };
    list_users_api_v1_auth_users_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_v1_auth_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_auth_users__user_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_api_v1_chat_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_api_v1_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_v1_chat__conv_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conv_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_api_v1_chat__conv_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conv_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_message_events_api_v1_chat__conv_id__messages__msg_id__events_get: {
        parameters: {
            query?: {
                /** @description Filter by event type */
                event_type?: string | null;
            };
            header?: never;
            path: {
                conv_id: string;
                msg_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_execution_api_v1_chat__conv_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conv_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_file_new_session_api_v1_artifacts_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_new_session_api_v1_artifacts_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_artifacts_api_v1_artifacts__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_file_api_v1_artifacts__session_id__upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_api_v1_artifacts__session_id__upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_artifact_api_v1_artifacts__session_id___artifact_id__export_get: {
        parameters: {
            query: {
                /** @description Export format (docx) */
                format: string;
            };
            header?: never;
            path: {
                session_id: string;
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_api_v1_artifacts__session_id___artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_api_v1_artifacts__session_id___artifact_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_version_api_v1_artifacts__session_id___artifact_id__versions__version__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                artifact_id: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_api_v1_stream__stream_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
